//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exam.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscando al estudiante en la base de datos.
        /// </summary>
        internal static string BuscandoEstudiante {
            get {
                return ResourceManager.GetString("BuscandoEstudiante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número total de caracteres suministrados coinciden.
        /// </summary>
        internal static string Coincide {
            get {
                return ResourceManager.GetString("Coincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------------------------------------------------------------------------------------------------.
        /// </summary>
        internal static string CortaCupon {
            get {
                return ResourceManager.GetString("CortaCupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creando .
        /// </summary>
        internal static string Creando {
            get {
                return ResourceManager.GetString("Creando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellidos:.
        /// </summary>
        internal static string EstudianteApellidos {
            get {
                return ResourceManager.GetString("EstudianteApellidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carné:.
        /// </summary>
        internal static string EstudianteCarne {
            get {
                return ResourceManager.GetString("EstudianteCarne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiante encontrado en la base de datos.
        /// </summary>
        internal static string EstudianteEncontrado {
            get {
                return ResourceManager.GetString("EstudianteEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante ha sido evaluado.
        /// </summary>
        internal static string EstudianteEvaluado {
            get {
                return ResourceManager.GetString("EstudianteEvaluado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante NO ha sido evaluado.
        /// </summary>
        internal static string EstudianteNoEvaluado {
            get {
                return ResourceManager.GetString("EstudianteNoEvaluado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plantilla de evaluación creada.
        /// </summary>
        internal static string EvaluacionCreada {
            get {
                return ResourceManager.GetString("EvaluacionCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluando la respuesta al examen.
        /// </summary>
        internal static string EvaluandoExamen {
            get {
                return ResourceManager.GetString("EvaluandoExamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo de examen asociado al estudiante.
        /// </summary>
        internal static string ExamenAsociado {
            get {
                return ResourceManager.GetString("ExamenAsociado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estructura del examen creada.
        /// </summary>
        internal static string ExamenCreado {
            get {
                return ResourceManager.GetString("ExamenCreado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examen generado en PDF.
        /// </summary>
        internal static string ExamenCreadoPDF {
            get {
                return ResourceManager.GetString("ExamenCreadoPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respuesta:.
        /// </summary>
        internal static string ExamenRespuesta {
            get {
                return ResourceManager.GetString("ExamenRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcta:.
        /// </summary>
        internal static string ExamenRespuestaCorrecta {
            get {
                return ResourceManager.GetString("ExamenRespuestaCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrado de preguntas.
        /// </summary>
        internal static string Filtrando {
            get {
                return ResourceManager.GetString("Filtrando", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo borrar el archivo .
        /// </summary>
        internal static string NoBorrado {
            get {
                return ResourceManager.GetString("NoBorrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número total de caracteres suministrados NO coinciden.
        /// </summary>
        internal static string NoCoincide {
            get {
                return ResourceManager.GetString("NoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estudiante no encontrado en las listas de clase. Por favor verificar..
        /// </summary>
        internal static string NoEnListas {
            get {
                return ResourceManager.GetString("NoEnListas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede evaluar el examen porque no hay estudiante asociado.
        /// </summary>
        internal static string NoEvaluableEstudiante {
            get {
                return ResourceManager.GetString("NoEvaluableEstudiante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede evaluar el estudiante porque no hay examen asociado.
        /// </summary>
        internal static string NoEvaluableExamen {
            get {
                return ResourceManager.GetString("NoEvaluableExamen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estudiante no puede ser evaluado hasta que la respuesta coincida en número de caracteres con la esperada.
        /// </summary>
        internal static string NoEvaluableRespuesta {
            get {
                return ResourceManager.GetString("NoEvaluableRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionando aleatoriamente .
        /// </summary>
        internal static string OrderAleatorio {
            get {
                return ResourceManager.GetString("OrderAleatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  preguntas aleatorias.
        /// </summary>
        internal static string PregAleatorias {
            get {
                return ResourceManager.GetString("PregAleatorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código QR suministrado no se encuentra en la base de datos.
        /// </summary>
        internal static string QRNoEncontrado {
            get {
                return ResourceManager.GetString("QRNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccionando .
        /// </summary>
        internal static string Seleccionando {
            get {
                return ResourceManager.GetString("Seleccionando", resourceCulture);
            }
        }
    }
}
